### ISSUE TITLE
npm start的时候报这个错，请问是

### ISSUE THREAD

**Issue by zhxsh** [Kim09AI/react-juejin#8]
Error: Cannot find module '../../dist/asyncCommonCss'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (D:\项目\practice\react-juejin-master\server\ssr\render.js:11:22)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)

**Comment by Kim09AI** [comment]
这是没有找到该文件，要先执行`npm run build`再`npm start`
